import manage1 from "../../assets/Home1/manage-1.webp";
import manage2 from "../../assets/Home1/design-1.webp";
import manage3 from "../../assets/Home1/finance-1.webp";
import manage4 from "../../assets/Home1/manage-4.webp";
import manage5 from "../../assets/Home1/manage-2.webp";
import manage6 from "../../assets/Home1/development-2.webp";
import design1 from "../../assets/Home1/design-3.webp";
import design2 from "../../assets/Home1/design-2.webp";
import development1 from "../../assets/Home1/development-3.webp";
import development2 from "../../assets/Home1/development-1.webp";
import Finance1 from "../../assets/Home1/finance.webp";
import submanage from "../../assets/Home1/submanage.webp";
import stars from "../../assets/Home1/stars.svg";
import bookIcon from "../../assets/Home1/bookicon.svg";
import prof from "../../assets/Home1/prof.svg";
export const CoursesData = {
  "All courses": [
    {
      img: manage1,
      paid: "Free",
      title: "MANAGEMENT",
      description: "Crisis management and problem-solving strategies",
      stars: stars,
      rate: "4.88(210)",
      bookIcon: bookIcon,
      btn1: "6 Lessons",
      prof: prof,
      btn2: "8k Enroled",
      btn3: "Courese Details",
      btn4: "Enroll",
    },
    {
      img: manage2,
      paid: "Free",
      title: "DESIGN",
      description: "Advanced photoshop techniques for designers",
      stars: stars,
      rate: "5.00(2k)",
      bookIcon: bookIcon,
      btn1: "8 Lessons",
      prof: prof,
      btn2: "25k Enroled",
      btn3: "Courese Details",
      btn4: "Enroll",
    },
    {
      img: manage3,
      paid: "Free",
      title: "FINANCE",
      description: "Operations management and process improvement",
      stars: stars,
      rate: "5.0(812)",
      bookIcon: bookIcon,
      btn1: "12 Lessons",
      prof: prof,
      btn2: "23k Enroled",
      btn3: "Courese Details",
      btn4: "Enroll",
    },
    {
      img: manage4,
      paid: "Free",
      title: "DEVELOPMENT",
      description: "Database integration with MongoDB",
      stars: stars,
      rate: "4.49(756)",
      bookIcon: bookIcon,
      btn1: "10 Lessons",
      prof: prof,
      btn2: "7k Enroled",
      btn3: "Courese Details",
      btn4: "Enroll",
    },
    {
      img: manage5,
      paid: "Free",
      title: "MANAGEMENT",
      description: "Risk management and business continuity",
      stars: stars,
      rate: "4.88(210)",
      bookIcon: bookIcon,
      btn1: "3 Lessons",
      prof: prof,
      btn2: "8k Enroled",
      btn3: "Courese Details",
      btn4: "Enroll",
    },
    {
      img: manage6,
      paid: "$56",
      title: "DEVELOPMENT",
      description: "Risk management and business continuity",
      stars: stars,
      rate: " 5.0(985)",
      bookIcon: bookIcon,
      btn1: "12 Lessons",
      prof: prof,
      btn2: "22k Enroled",
      btn3: "Courese Details",
      btn4: "Enroll",
    },
  ],
  Design: [
    {
      img: design1,
      paid: "$99",
      title: "DESIGN",
      description: "Design systems and pattern libraries",
      stars: stars,
      rate: "5.00(1.2k)",
      bookIcon: bookIcon,
      btn1: "8 Lessons",
      prof: prof,
      btn2: "25k Enroled",
      btn3: "Courese Details",
      btn4: "Enroll",
    },
    {
      img: design2,
      paid: "$79",
      title: "DESIGN",
      description: "Design systems and pattern libraries",
      stars: stars,
      rate: "4.49(756)",
      bookIcon: bookIcon,
      btn1: "12 Lessons",
      prof: prof,
      btn2: "23k Enroled",
      btn3: "Courese Details",
      btn4: "Enroll",
    },
    {
      img: manage2,
      paid: "Free",
      title: "DESIGN",
      description: "Advanced photoshop techniques for designers",
      stars: stars,
      rate: "5.00(1.2k)",
      bookIcon: bookIcon,
      btn1: "8 Lessons",
      prof: prof,
      btn2: "25k Enroled",
      btn3: "Courese Details",
      btn4: "Enroll",
    },
  ],
  Development: [
    {
      img: development1,
      paid: "Free",
      title: "DEVELOPMENT",
      description: "Design systems and pattern libraries",
      stars: stars,
      rate: "5.00(328)",
      bookIcon: bookIcon,
      btn1: "6 Lessons",
      prof: prof,
      btn2: "12k Enroled",
      btn3: "Courese Details",
      btn4: "Enroll",
    },

    {
      img: development2,
      paid: "$59",
      title: "DEVELOPMENT",
      description: "Database integration with MongoDB",
      stars: stars,
      rate: "4.49(756)",
      bookIcon: bookIcon,
      btn1: "10 Lessons",
      prof: prof,
      btn2: "7k Enroled",
      btn3: "Courese Details",
      btn4: "Enroll",
    },
    {
      img: manage6,
      paid: "$72",
      title: "DEVELOPMENT",
      description: "Full-stack development with the MERN stack",
      stars: stars,
      rate: "5.00(985)",
      bookIcon: bookIcon,
      btn1: "12 Lessons",
      prof: prof,
      btn2: "22k Enroled",
      btn3: "Courese Details",
      btn4: "Enroll",
    },
  ],
  Management: [
    {
      img: manage5,
      paid: "$49",
      title: "MANAGEMENT",
      description: "Risk management and business continuity",
      stars: stars,
      rate: "4.88(210)",
      bookIcon: bookIcon,
      btn1: "3 Lessons",
      prof: prof,
      btn2: "8k Enroled",
      btn3: "Courese Details",
      btn4: "Enroll",
    },
    {
      img: submanage,
      paid: "$49",
      title: "MANAGEMENT",
      description: "Grow your brand and reach your audience",
      stars: stars,
      rate: "4.88(210)",
      bookIcon: bookIcon,
      btn1: "10 Lessons",
      prof: prof,
      btn2: "8k Enroled",
      btn3: "Courese Details",
      btn4: "Enroll",
    },
  ],
  Finance: [
    {
      img: manage3,
      paid: "Free",
      title: "FINANCE",
      description: "Risk management and business continuity",
      stars: stars,
      rate: "5.00(812)",
      bookIcon: bookIcon,
      btn1: "12 Lessons",
      prof: prof,
      btn2: "23k Enroled",
      btn3: "Courese Details",
      btn4: "Enroll",
    },
    {
      img: Finance1,
      paid: "$99",
      title: "FINANCE",
      description: "The complete guide to personal and business finance",
      stars: stars,
      rate: "4.88(210)",
      bookIcon: bookIcon,
      btn1: "10 Lessons",
      prof: prof,
      btn2: "8k Enroled",
      btn3: "Courese Details",
      btn4: "Enroll",
    },
  ],
};
// data for cooursesone page
export const allcoursesdata = [
  {
    img: manage1,
    paid: "Free",
    title: "MANAGEMENT",
    description: "Crisis management and problem-solving strategies",
    stars: stars,
    rate: "4.88(210)",
    bookIcon: bookIcon,
    btn1: "6 Lessons",
    prof: prof,
    btn2: "8k Enroled",
    btn3: "Courese Details",
    btn4: "Enroll",
  },
  {
    img: manage2,
    paid: "$55",
    title: "DESIGN",
    description: "Advanced photoshop techniques for designers",
    stars: stars,
    rate: "5.00(2k)",
    bookIcon: bookIcon,
    btn1: "8 Lessons",
    prof: prof,
    btn2: "25k Enroled",
    btn3: "Courese Details",
    btn4: "Enroll",
  },
  {
    img: manage3,
    paid: "Free",
    title: "FINANCE",
    description: "Operations management and process improvement",
    stars: stars,
    rate: "5.0(812)",
    bookIcon: bookIcon,
    btn1: "12 Lessons",
    prof: prof,
    btn2: "23k Enroled",
    btn3: "Courese Details",
    btn4: "Enroll",
  },
  {
    img: manage4,
    paid: "$66",
    title: "DEVELOPMENT",
    description: "Database integration with MongoDB",
    stars: stars,
    rate: "4.49(756)",
    bookIcon: bookIcon,
    btn1: "10 Lessons",
    prof: prof,
    btn2: "7k Enroled",
    btn3: "Courese Details",
    btn4: "Enroll",
  },
  {
    img: manage5,
    paid: "Free",
    title: "MANAGEMENT",
    description: "Risk management and business continuity",
    stars: stars,
    rate: "4.88(210)",
    bookIcon: bookIcon,
    btn1: "3 Lessons",
    prof: prof,
    btn2: "8k Enroled",
    btn3: "Courese Details",
    btn4: "Enroll",
  },
  {
    img: manage6,
    paid: "$56",
    title: "DEVELOPMENT",
    description: "Risk management and business continuity",
    stars: stars,
    rate: " 5.0(985)",
    bookIcon: bookIcon,
    btn1: "12 Lessons",
    prof: prof,
    btn2: "22k Enroled",
    btn3: "Courese Details",
    btn4: "Enroll",
  },
];

export const allcoursesdata1 = [
  {
    img: manage2,
    paid: "$55",
    title: "DESIGN",
    description: "Advanced photoshop techniques for designers",
    stars: stars,
    rate: "5.00(2k)",
    bookIcon: bookIcon,
    btn1: "8 Lessons",
    prof: prof,
    btn2: "25k Enroled",
    btn3: "Courese Details",
    btn4: "Enroll",
  },

  {
    img: manage1,
    paid: "Free",
    title: "MANAGEMENT",
    description: "Crisis management and problem-solving strategies",
    stars: stars,
    rate: "4.88(210)",
    bookIcon: bookIcon,
    btn1: "6 Lessons",
    prof: prof,
    btn2: "8k Enroled",
    btn3: "Courese Details",
    btn4: "Enroll",
  },
  {
    img: manage4,
    paid: "$66",
    title: "DEVELOPMENT",
    description: "Database integration with MongoDB",
    stars: stars,
    rate: "4.49(756)",
    bookIcon: bookIcon,
    btn1: "10 Lessons",
    prof: prof,
    btn2: "7k Enroled",
    btn3: "Courese Details",
    btn4: "Enroll",
  },
  {
    img: manage5,
    paid: "Free",
    title: "MANAGEMENT",
    description: "Risk management and business continuity",
    stars: stars,
    rate: "4.88(210)",
    bookIcon: bookIcon,
    btn1: "3 Lessons",
    prof: prof,
    btn2: "8k Enroled",
    btn3: "Courese Details",
    btn4: "Enroll",
  },
  {
    img: manage6,
    paid: "$56",
    title: "DEVELOPMENT",
    description: "Risk management and business continuity",
    stars: stars,
    rate: " 5.0(985)",
    bookIcon: bookIcon,
    btn1: "12 Lessons",
    prof: prof,
    btn2: "22k Enroled",
    btn3: "Courese Details",
    btn4: "Enroll",
  },
  {
    img: manage3,
    paid: "Free",
    title: "FINANCE",
    description: "Operations management and process improvement",
    stars: stars,
    rate: "5.0(812)",
    bookIcon: bookIcon,
    btn1: "12 Lessons",
    prof: prof,
    btn2: "23k Enroled",
    btn3: "Courese Details",
    btn4: "Enroll",
  },
];
