import icon from "../../../../assets/Home1/check.svg";
export const pricingdata = [
  {
    title: "Basic",
    subtitle: "Lorem ipsum dolor sit amet consectetur erat ipsum non.",
    pricem: "$199",
    pricey: "$133",
    month: "Month",
    icon: icon,
    li1: "Access to 10+ top courses",
    li2: "Certification prep",
    li3: "Customizable content",
    li4: "AI-powered coding",
    btn: "Subscrib This Plan",
  },
  {
    title: "Standard",
    subtitle: "Lorem ipsum dolor sit amet consectetur erat ipsum non.",
    pricem: "$199",
    pricey: "$133",
    month: "Month",
    icon: icon,
    li1: "Access to 10+ top courses",
    li2: "Certification prep",
    li3: "Customizable content",
    li4: "AI-powered coding",
    btn: "Subscrib This Plan",
  },
  {
    title: "Primeum",
    subtitle: "Lorem ipsum dolor sit amet consectetur erat ipsum non.",
    pricem: "$699",
    pricey: "$679",
    month: "Month",
    icon: icon,
    li1: "Access to 10+ top courses",
    li2: "Certification prep",
    li3: "Customizable content",
    li4: "AI-powered coding",
    nested: {
      li5: "Analytics and adoption reports",
      icon1: icon,
      btn2: "Subscrib This Plan",
    },
  },
];
